name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  preparing-k3s-cluster:
    name: Spinning up a k3s cluster
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k3s-version: [ v1.22.5 ]
        # k3s-version: [v1.20.2, v1.19.2, v1.18.9, v1.17.11, v1.16.15]
    steps:
      - name: Install K3D
        run: |
          set -x
          curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
          sudo mkdir -p $HOME/.kube && sudo chown -R runner $HOME/.kube
          k3d cluster create --servers 3 --image rancher/k3s:${{ matrix.k3s-version }}-k3s1
          kubectl version
          k3d version
          kubectl get nodes
          kubectl get pods
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2
          args: --timeout 10m --verbose
      - name: Run unit test
        run: |
          go test ./...
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag hello-go-http:v1.0
